server :
  port : 9011
  address: 0.0.0.0


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Yuanqu
  datasource:

    url: jdbc:mysql://120.24.109.29:3306/Yuanqu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 3 # ?????????????
      max-active: 10 # ???????
      min-idle: 5 # ???????
      max-wait: 60000 # ????????????????
      time-between-eviction-runs-millis: 60000 # ???????????????????????????????
      min-evictable-idle-time-millis: 300000 # ????????????????
      validation-query: SELECT 1 # ???????????sql??????????
      # ?????true?????????????????????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
      test-while-idle: true
      test-on-borrow: false # ???????validationQuery?????????????????????
      test-on-return: false  # ???????validationQuery?????????????????????
      pool-prepared-statements: false # ????preparedStatement????PSCache?PSCache???????????????????oracle??mysql??????

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB



#mybatis-flux
mybatis-flex:
  datasource:
    #    check-type: false
    KK:
      url: jdbc:mysql://120.24.109.29:3306/Yuanqu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: Aa123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 3 # ?????????????
        max-active: 10 # ???????
        min-idle: 5 # ???????
        max-wait: 60000 # ????????????????
        time-between-eviction-runs-millis: 60000 # ???????????????????????????????
        min-evictable-idle-time-millis: 300000 # ????????????????
        validation-query: SELECT 1 # ???????????sql??????????
        # ?????true?????????????????????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
        test-while-idle: true
        test-on-borrow: false # ???????validationQuery?????????????????????
        test-on-return: false  # ???????validationQuery?????????????????????
        pool-prepared-statements: false # ????preparedStatement????PSCache?PSCache???????????????????oracle??mysql??????
    FY:
      url: jdbc:mysql://120.24.109.29:3306/udyk_community?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: Aa123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 3 # ?????????????
        max-active: 10 # ???????
        min-idle: 5 # ???????
        max-wait: 60000 # ????????????????
        time-between-eviction-runs-millis: 60000 # ???????????????????????????????
        min-evictable-idle-time-millis: 300000 # ????????????????
        validation-query: SELECT 1 # ???????????sql??????????
        # ?????true?????????????????????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
        test-while-idle: true
        test-on-borrow: false # ???????validationQuery?????????????????????
        test-on-return: false  # ???????validationQuery?????????????????????
        pool-prepared-statements: false # ????preparedStatement????PSCache?PSCache???????????????????oracle??mysql??????

  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/example/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  global-config:
#    db-config:
#      id-type: auto

mybatis-plus:

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# knife4j ??????
knife4j:
  # ???? Knife4j ????
  enable: true  # ??? true ????????
  # ??????
  production: false  # ??? true ??????????????? false ??????????????????
  setting:
    language: zh_cn
# ????
management:
  endpoint:
    metrics:
      enabled: true  #??metrics,????????
    prometheus:
      enabled: true  #???????,????????
  metrics:
    tags:
      application: ${spring.application.name} #?????
  endpoints:
    web:
      exposure:
        include: "*" #??????
  prometheus:
    metrics:
      export:
        enabled: true

# ????
security:
  jwt:
    # JWT ??
    key: kkSource
    # JWT ???(????)
    ttl: 7200
  # ?????
  ignore-urls:
    - /**
    - /H5/**
    - /Platform/**
    - /auth/**
    - /doc.html/**
    - /swagger-resources/**
    - /swagger-ui/**
    - /swagger-ui.html
    - /webjars/**
    - /v3/api-docs/**
    - /sys_user/forbidden/**
    - /sys_user/unforbidden/**


wx:
  appid: wx48a36db199ce3dc9
  secret: 27e6bb08b12c2fa8bd2a9de2e55f841f


rocketmq:
  name-server: 120.24.109.29:9876
  producer:
    group: platform
  #    send-message-timeout: 10000 # 10???
  consumer:
    group: platform


